# Generated by Django 6.1 on 2026-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('badge_status', models.CharField(choices=[('LIVRABLE', 'Livrable Immédiatement'), ('OFF_MARKET', 'Lancement Off-Market'), ('INVESTISSEMENT', 'Investissement Pro')], default='LIVRABLE', max_length=50)),
                ('city', models.CharField(help_text='Ex: Casablanca, Rabat', max_length=100)),
                ('district', models.CharField(help_text='Ex: Anfa, Souissi, CFC', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en DH (Ex: 2400000)', max_digits=12)),
                ('price_display', models.CharField(help_text='Ex: À partir de 2.4 MDH ou Sur Devis Pro', max_length=50)),
                ('property_type', models.CharField(choices=[('Appartement', 'Appartement Haut Standing'), ('Villa', 'Villa Moderne / Luxe'), ('Bureaux', 'Bureaux & Commerces')], default='Appartement', max_length=50)),
                ('description', models.TextField()),
                ('rooms', models.CharField(help_text='Ex: 2-4 Ch. ou 5 Ch.', max_length=50)),
                ('surface', models.CharField(help_text='Ex: 82-185 m²', max_length=50)),
                ('feature_tag', models.CharField(help_text='Ex: Piscine, Jardin, Parking 3N', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('pdf_brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
