# Generated by Django 6.1 on 2026-08-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pdf_brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/', verbose_name='Brochure PDF'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Image de Galerie')),
                ('caption', models.CharField(blank=True, help_text='Légende optionnelle (ex: Salon, Cuisine)', max_length=150, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.property')),
            ],
        ),
    ]
