# Generated by Django 6.1 on 2026-08-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_propertyimage_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('category', models.CharField(choices=[('salons', 'Salons & Canapés'), ('tables', 'Tables & Chaises'), ('luminaires', 'Luminaires'), ('deco', 'Décoration & Accessoires')], default='salons', max_length=50, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancien Prix (Optionnel)')),
                ('badge_tag', models.CharField(blank=True, help_text='Ex: Top Vente, Sur-Mesure, Promo', max_length=50, null=True, verbose_name='Badge / Tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture/', verbose_name='Image du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
