# Generated by Django 6.1 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_furnitureproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du Produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancien Prix (DH)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('badge_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge (ex: PROMO, NEW)')),
                ('category', models.CharField(default='MOBILIER LUXE', max_length=100, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
