# Generated by Django 6.1 on 2026-08-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='image_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image Secondaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image Principale'),
        ),
    ]
