# Generated by Django 6.1 on 2026-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_category_product_image_secondary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Casablanca', help_text='Ex: Casablanca, Rabat', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(default='Anfa', help_text='Ex: Anfa, Souissi, CFC', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix en DH (Ex: 2400000)', max_digits=12),
        ),
    ]
