# Generated by Django 6.1 on 2026-08-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_property_city_alter_property_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom Complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone / WhatsApp')),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine souhaité')),
                ('pack_type', models.CharField(choices=[('starter', 'Pack Starter - Site Vitrine'), ('pro', 'Pack Pro - Vitrine & Admin Panel'), ('elite', 'Pack Elite - Sur-Mesure')], max_length=20, verbose_name='Type de Pack')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (DH)')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
