# Generated by Django 6.1 on 2026-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='template_choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle choisi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pack_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=20, verbose_name='Type de Pack'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
