# Generated by Django 6.1 on 2026-08-31 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_template_choice_alter_order_pack_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templateproduct',
            name='demo_url',
            field=models.CharField(help_text='Nom de la vue Django (ex: store:demo_luxury_living)', max_length=200),
        ),
    ]
